FROM node:23 AS builder

RUN apt-get update && apt-get install -y libdbus-1-3 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/Affirmatech/MeshSense.git .

WORKDIR /app/api
RUN npm install
RUN npm run build

WORKDIR /app/ui
RUN npm install
RUN npm run build

FROM node:23-alpine
EXPOSE 5920

RUN apk --no-cache add dbus-dev
COPY --from=builder /app/ /app/

WORKDIR /app/api/dist
CMD ["node", "index.cjs"]
